// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyd5mocfsa2cjS5l0s5Y4ayUQx8X-kX8',
    appId: '1:340569211116:web:b045e6a5a2a88ebc7ca5c9',
    messagingSenderId: '340569211116',
    projectId: 'wordplay-6fd2a',
    authDomain: 'wordplay-6fd2a.firebaseapp.com',
    storageBucket: 'wordplay-6fd2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_QAaUN-C80_pmJysfR9niy2UzSo7DMs',
    appId: '1:340569211116:android:8071b03c0182ef417ca5c9',
    messagingSenderId: '340569211116',
    projectId: 'wordplay-6fd2a',
    storageBucket: 'wordplay-6fd2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdOtqkz9zo09E8ajYZb5QEOgzapjbUCu0',
    appId: '1:340569211116:ios:0cd937a2c4d094ae7ca5c9',
    messagingSenderId: '340569211116',
    projectId: 'wordplay-6fd2a',
    storageBucket: 'wordplay-6fd2a.appspot.com',
    iosBundleId: 'com.example.wordsBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdOtqkz9zo09E8ajYZb5QEOgzapjbUCu0',
    appId: '1:340569211116:ios:d614b408bd18a4c57ca5c9',
    messagingSenderId: '340569211116',
    projectId: 'wordplay-6fd2a',
    storageBucket: 'wordplay-6fd2a.appspot.com',
    iosBundleId: 'com.example.wordsBase.RunnerTests',
  );
}
